# Generated by Django 4.0.4 on 2022-08-10 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='CategoryIcons/')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('password', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('datejoin', models.DateField(auto_now_add=True)),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='FreelancerProfiles/')),
                ('isauthenticated', models.BooleanField(default=False)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.city')),
            ],
        ),
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('rate', models.FloatField(default=2.5)),
                ('leastprice', models.FloatField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('rate', models.FloatField(default=2.5)),
                ('successfulnumbers', models.IntegerField(default=0)),
                ('datejoin', models.DateField(auto_now_add=True)),
                ('website', models.TextField()),
                ('instalink', models.TextField()),
                ('isapproved', models.BooleanField(default=False)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='GroupIcons/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ispaid', models.BooleanField(default=False)),
                ('tracknumber', models.TextField()),
                ('deliverytime', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('price', models.FloatField(default=0)),
                ('deliverytime', models.IntegerField(default=1)),
                ('numberofrevisions', models.IntegerField(default=1)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gig')),
            ],
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=11)),
                ('issued', models.DateTimeField(auto_now_add=True)),
                ('valid', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128)),
                ('validdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('gigs', models.ManyToManyField(to='api.gig')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='SubCategoryIcons/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=11)),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='ShopProfiles/')),
                ('datejoin', models.DateField(auto_now_add=True)),
                ('instalink', models.TextField()),
                ('website', models.TextField()),
                ('description', models.TextField()),
                ('businesstype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.businesstype')),
                ('token', models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.token')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=2.5)),
                ('description', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('Package', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.package')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.order')),
            ],
        ),
        migrations.CreateModel(
            name='PackageDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('value', models.TextField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.package')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.package'),
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.shop'),
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isadmin', models.BooleanField(default=False)),
                ('datejoin', models.DateField(auto_now_add=True)),
                ('role', models.TextField()),
                ('share', models.FloatField()),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.freelancer')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='followers',
            field=models.ManyToManyField(to='api.shop'),
        ),
        migrations.AddField(
            model_name='group',
            name='subcategories',
            field=models.ManyToManyField(to='api.subcategory'),
        ),
        migrations.CreateModel(
            name='GigFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='GigFiles/')),
                ('priority', models.IntegerField(default=1)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.gig')),
            ],
        ),
        migrations.AddField(
            model_name='gig',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.group'),
        ),
        migrations.AddField(
            model_name='gig',
            name='subcat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.subcategory'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='token',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.token'),
        ),
        migrations.CreateModel(
            name='FreeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='FreeFiles/')),
                ('description', models.TextField()),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.freelancer')),
            ],
        ),
        migrations.AddField(
            model_name='businesstype',
            name='subcategories',
            field=models.ManyToManyField(to='api.subcategory'),
        ),
    ]
