# Generated by Django 4.0.4 on 2022-06-02 13:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='CategoryIcons')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('address', models.TextField(blank=True, null=True)),
                ('rate', models.FloatField(default=0.0)),
                ('level', models.IntegerField(default=1)),
                ('datejoin', models.DateTimeField(default=datetime.datetime(2022, 6, 2, 13, 48, 58, 74106))),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='FreelancerProfiles')),
                ('numberofjobs', models.IntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.city')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('deliverytime', models.IntegerField(default=1)),
                ('numberofrevisions', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=11)),
                ('issued', models.DateTimeField(default=datetime.datetime(2022, 6, 2, 13, 48, 58, 72996))),
                ('valid', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='SubCategoryIcons')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128)),
                ('validdate', models.DateTimeField(default=datetime.datetime(2022, 6, 2, 13, 48, 58, 71884))),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('rate', models.FloatField(default=0.0)),
                ('numberofrates', models.IntegerField(default=0)),
                ('leastprice', models.IntegerField(default=10)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.freelancer')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='WorkFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='WorkFiles')),
                ('priority', models.IntegerField(default=1)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.work')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('works', models.ManyToManyField(to='api.work')),
            ],
        ),
        migrations.CreateModel(
            name='PackageDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('value', models.TextField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.package')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.work'),
        ),
        migrations.CreateModel(
            name='MainUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationalcode', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=11)),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='UserProfiles')),
                ('isauthenticated', models.BooleanField(default=False)),
                ('datejoin', models.DateTimeField(default=datetime.datetime(2022, 6, 2, 13, 48, 58, 72294))),
                ('token', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.token')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='freelancer',
            name='token',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.token'),
        ),
        migrations.CreateModel(
            name='FreeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='FreeFiles')),
                ('description', models.TextField(blank=True, null=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.freelancer')),
            ],
        ),
    ]
