# Generated by Django 4.0.4 on 2022-08-27 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_groupfile_delete_freefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GigMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isadmin', models.BooleanField(default=False)),
                ('datejoin', models.DateField(auto_now_add=True)),
                ('role', models.TextField()),
                ('share', models.FloatField()),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gig')),
                ('groupmember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.groupmember')),
            ],
        ),
    ]
