# Generated by Django 4.0.4 on 2022-08-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_gigmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigmember',
            name='share',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='share',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
