# Generated by Django 4.0.4 on 2022-08-31 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_gigmember_share_alter_groupmember_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='datejoin',
            field=models.DateField(default=datetime.date(2022, 8, 31)),
        ),
        migrations.AlterField(
            model_name='gigmember',
            name='datejoin',
            field=models.DateField(default=datetime.date(2022, 8, 31)),
        ),
        migrations.AlterField(
            model_name='group',
            name='datejoin',
            field=models.DateField(default=datetime.date(2022, 8, 31)),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='datejoin',
            field=models.DateField(default=datetime.date(2022, 8, 31)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 31, 8, 36, 42, 55291)),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliverytime',
            field=models.DateField(default=datetime.date(2022, 8, 31)),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.date(2022, 8, 31)),
        ),
        migrations.AlterField(
            model_name='shop',
            name='datejoin',
            field=models.DateField(default=datetime.date(2022, 8, 31)),
        ),
        migrations.AlterField(
            model_name='sms',
            name='issued',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 31, 8, 36, 42, 58461)),
        ),
        migrations.AlterField(
            model_name='sms',
            name='valid',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 31, 8, 36, 42, 58485)),
        ),
        migrations.AlterField(
            model_name='token',
            name='validdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 31, 8, 36, 42, 45946)),
        ),
    ]
