# Generated by Django 4.0.4 on 2022-11-26 09:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_freelancer_datejoin_alter_gigmember_datejoin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='FreelancerResumes/'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='subcat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.subcategory'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='datejoin',
            field=models.DateField(default=datetime.date(2022, 11, 26)),
        ),
        migrations.AlterField(
            model_name='gigmember',
            name='datejoin',
            field=models.DateField(default=datetime.date(2022, 11, 26)),
        ),
        migrations.AlterField(
            model_name='group',
            name='datejoin',
            field=models.DateField(default=datetime.date(2022, 11, 26)),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='datejoin',
            field=models.DateField(default=datetime.date(2022, 11, 26)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 9, 12, 9, 452932)),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliverytime',
            field=models.DateField(default=datetime.date(2022, 11, 26)),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.date(2022, 11, 26)),
        ),
        migrations.AlterField(
            model_name='shop',
            name='datejoin',
            field=models.DateField(default=datetime.date(2022, 11, 26)),
        ),
        migrations.AlterField(
            model_name='sms',
            name='issued',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 9, 12, 9, 455213)),
        ),
        migrations.AlterField(
            model_name='sms',
            name='valid',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 9, 12, 9, 455234)),
        ),
        migrations.AlterField(
            model_name='token',
            name='validdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 9, 12, 9, 444520)),
        ),
    ]
