# Generated by Django 4.0.4 on 2022-12-01 09:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_freelancer_resume_freelancer_subcat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='linkedin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cardnumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='datejoin',
            field=models.DateField(default=datetime.date(2022, 12, 1)),
        ),
        migrations.AlterField(
            model_name='gigmember',
            name='datejoin',
            field=models.DateField(default=datetime.date(2022, 12, 1)),
        ),
        migrations.AlterField(
            model_name='group',
            name='datejoin',
            field=models.DateField(default=datetime.date(2022, 12, 1)),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='datejoin',
            field=models.DateField(default=datetime.date(2022, 12, 1)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 9, 28, 33, 577836)),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliverytime',
            field=models.DateField(default=datetime.date(2022, 12, 1)),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracknumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.date(2022, 12, 1)),
        ),
        migrations.AlterField(
            model_name='shop',
            name='datejoin',
            field=models.DateField(default=datetime.date(2022, 12, 1)),
        ),
        migrations.AlterField(
            model_name='sms',
            name='issued',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 9, 28, 33, 579595)),
        ),
        migrations.AlterField(
            model_name='sms',
            name='valid',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 9, 28, 33, 579611)),
        ),
        migrations.AlterField(
            model_name='token',
            name='validdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 9, 28, 33, 569028)),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('role', models.TextField()),
                ('date', models.DateField(default=datetime.date(2022, 12, 1))),
                ('reference', models.TextField(blank=True, max_length=10, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.freelancer')),
            ],
        ),
    ]
